### ISSUE TITLE
noise2net always uses a pre-trained ResNet50

### ISSUE THREAD

**Issue by amodas** [hendrycks/imagenet-r#4]
Hi,

It seems that at [Line173](https://github.com/hendrycks/imagenet-r/blob/3131cacee97c407bd2ecea15846a67817a64f924/DeepAugment/train_noise2net.py#L173) of train_noise2net.py the ``pretrained`` argument of ResNet50 is always set to ``True``.

Is this simply a bug or something we should take into account? As far as I understand, the results of the paper do not consider an ImageNet pre-trained classifier, right?

Thanks,
Apostolos

**Comment by hendrycks** [comment]
noise2net models were pretrained for a portion of the results at least, following AugMix. (However, this may have been from pre-experimentation.) We hardcoded pretrained=True so that things behaved correctly if we forgot the pretrained flag, though of course such hardcoding is not a best coding practice.
